version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/flask-app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
